### ISSUE TITLE
S3FileField inaccessible during save call after super.save

### ISSUE THREAD

**Issue by banesullivan** [girder/django-s3-file-field#105]
I am encountering an issue where the `S3FileField` might not be saved during the model’s save call… is there some sort of async task going on there? For example:

```py
class ArbitraryFile(models.Model):
    file = S3FileField()

    def save(self, *args, **kwargs):
        super(ArbitraryFile, self).save(*args, **kwargs)
        # ^^ should have saved the `file` field, right?
        # However this line will error:
        with self.file.open('rb'):
            pass
```

Then go to your app's admin page and try to upload a file. You'll get the error: `AttributeError: 'S3FakeFile' object has no attribute 'open'`

-------

This is an issue I am experiencing in https://github.com/ResonantGeoData/ResonantGeoData/issues/131 both locally and deployed... I'm actually not sure if its the same error on the deployed site as all I get is `"Server Error (500)"` without a log.

In ResonantGeoData, we have `ChecksumFile ` and `ArbitraryFile` models here:

https://github.com/ResonantGeoData/ResonantGeoData/blob/6487c8e216c9ae32c584eefa9975e5a1f316cfb2/rgd/geodata/models/common.py#L58-L133

The `ChecksumFile` model is an "abstract" model defining the `save` call that needs to access the `S3FileField` for computing a checksum after saving. The `ChecksumFile` class requires the child class to define the `S3FileField`... hopefully, this mess doesn't distract from the problem.

If you launch our app and try to upload any file to `ArbitraryFile` via the admin interface, checking the `compute_checksum` box, you will get the mentioned error. Full traceback in details below. 

<details>

here is a log from the implementation in ResonantGeoData
```
django_1    | [17:53:03] ERROR    Internal Server Error:                            log.py:224
django_1    |                     /admin/geodata/arbitraryfile/add/
django_1    |                     Traceback (most recent call last):
django_1    |                       File "/usr/local/lib/python3.8/site-packages/dj
django_1    |                     ango/core/handlers/exception.py", line 47, in
django_1    |                     inner
django_1    |                         response = get_response(request)
django_1    |                       File "/usr/local/lib/python3.8/site-packages/dj
django_1    |                     ango/core/handlers/base.py", line 179, in
django_1    |                     _get_response
django_1    |                         response = wrapped_callback(request,
django_1    |                     *callback_args, **callback_kwargs)
django_1    |                       File "/usr/local/lib/python3.8/site-packages/dj
django_1    |                     ango/contrib/admin/options.py", line 614, in
django_1    |                     wrapper
django_1    |                         return
django_1    |                     self.admin_site.admin_view(view)(*args, **kwargs)
django_1    |                       File "/usr/local/lib/python3.8/site-packages/dj
django_1    |                     ango/utils/decorators.py", line 130, in
django_1    |                     _wrapped_view
django_1    |                         response = view_func(request, *args,
django_1    |                     **kwargs)
django_1    |                       File "/usr/local/lib/python3.8/site-packages/dj
django_1    |                     ango/views/decorators/cache.py", line 44, in
django_1    |                     _wrapped_view_func
django_1    |                         response = view_func(request, *args,
django_1    |                     **kwargs)
django_1    |                       File "/usr/local/lib/python3.8/site-packages/dj
django_1    |                     ango/contrib/admin/sites.py", line 233, in inner
django_1    |                         return view(request, *args, **kwargs)
django_1    |                       File "/usr/local/lib/python3.8/site-packages/dj
django_1    |                     ango/contrib/admin/options.py", line 1653, in
django_1    |                     add_view
django_1    |                         return self.changeform_view(request, None,
django_1    |                     form_url, extra_context)
django_1    |                       File "/usr/local/lib/python3.8/site-packages/dj
django_1    |                     ango/utils/decorators.py", line 43, in _wrapper
django_1    |                         return bound_method(*args, **kwargs)
django_1    |                       File "/usr/local/lib/python3.8/site-packages/dj
django_1    |                     ango/utils/decorators.py", line 130, in
django_1    |                     _wrapped_view
django_1    |                         response = view_func(request, *args,
django_1    |                     **kwargs)
django_1    |                       File "/usr/local/lib/python3.8/site-packages/dj
django_1    |                     ango/contrib/admin/options.py", line 1534, in
django_1    |                     changeform_view
django_1    |                         return self._changeform_view(request,
django_1    |                     object_id, form_url, extra_context)
django_1    |                       File "/usr/local/lib/python3.8/site-packages/dj
django_1    |                     ango/contrib/admin/options.py", line 1580, in
django_1    |                     _changeform_view
django_1    |                         self.save_model(request, new_object, form,
django_1    |                     not add)
django_1    |                       File "/usr/local/lib/python3.8/site-packages/dj
django_1    |                     ango/contrib/admin/options.py", line 1093, in
django_1    |                     save_model
django_1    |                         obj.save()
django_1    |                       File "/opt/django-project/rgd/geodata/models/co
django_1    |                     mmon.py", line 115, in save
django_1    |                         self.update_checksum()
django_1    |                       File "/opt/django-project/rgd/geodata/models/co
django_1    |                     mmon.py", line 81, in update_checksum
django_1    |                         with _field_file_to_local_path(self.file) as
django_1    |                     file_path:
django_1    |                       File "/usr/local/lib/python3.8/contextlib.py",
django_1    |                     line 113, in __enter__
django_1    |                         return next(self.gen)
django_1    |                       File "/opt/django-project/rgd/utility.py", line
django_1    |                     22, in _field_file_to_local_path
django_1    |                         with field_file.open('rb'):
django_1    |                     AttributeError: 'S3FakeFile' object has no
django_1    |                     attribute 'open'
```

</details>

**Comment by banesullivan** [comment]
On a related note, if I try to do a `save(update_fields['...'])` on a model with an s3filefield immediately after creation, I get this error:

```
  File "/opt/django-project/rgd/geodata/models/common.py", line 33, in save
    super(ModifiableEntry, self).save(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 753, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 801, in save_base
    post_save.send(
  File "/usr/local/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 177, in send
    return [
  File "/usr/local/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 178, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/usr/local/lib/python3.8/site-packages/django_cleanup/handlers.py", line 44, in delete_old_post_save
    for field_name, new_file in cache.fields_for_model_instance(instance):
  File "/usr/local/lib/python3.8/site-packages/django_cleanup/cache.py", line 86, in fields_for_model_instance
    yield field_name, fieldfile.__class__(using, fieldfile.field, fieldfile.name)

Exception Type: AttributeError at /admin/geodata/fmvfile/add/
Exception Value: 'S3FakeFile' object has no attribute 'field'
```

experiencing in https://github.com/ResonantGeoData/ResonantGeoData/pull/179

**Comment by dchiquit** [comment]
`S3FileFields` are impersonations of normal Django `FileFields`. One big difference is that the actual bytes in the file have already been uploaded to S3, so they should not include that data in form submissions. However, a `File` like object still needs to be included in the form, so we wrote `S3FakeFile`, which basically mimics `File` except for the file data. Form submissions use the rest of the info in `S3FakeFile` to populate the field info when a form is saved to create a model.

The problem is that when `ArbitraryFile.save()` is called during form submission, its fields are populated from the form, so `file` is still an instance of `S3FakeFile`. If you were to load that `ArbitraryFile` from the DB at this point, it would correctly instantiate an `S3FieldFile` and I think everything would be fine.

For now, the easy solution is to just include `self.refresh_from_db()`  immediately after calling `super().save()`. I've reproduced the problem and that fixed it for me.

I don't see any convenient hooks to do that upstream, but I will keep digging.

**Comment by dchiquit** [comment]
^ That should fix it if approved.

**Comment by banesullivan** [comment]
Ah, thanks @dchiquit! This provides a ton of insight into what is happening and how to work around it. I will give the `refresh_from_db` a try in RGD but also look forward to #110 when that lands on a release

**Comment by banesullivan** [comment]
Update: that did the trick! thanks again!!
