### ISSUE TITLE
Occasional circular import error

### ISSUE THREAD

**Issue by danlamanna** [girder/django-s3-file-field#156]
Currently this line throws an uncaught import error only when code is being reloaded with django runserver. I have a difficult time reproducing this consistently, but I've run into it on multiple occasions across projects. https://github.com/girder/django-s3-file-field/blob/a9c860bdcd1f7a3dae27debf4aa2b626e95fab79/s3_file_field/_multipart.py#L123

I haven't figured out why it's only being triggered with the reloader quite yet.

```
[10:44:34] INFO     Watching for file changes with StatReloader                                                                                                             autoreload.py:617
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 950, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dan/.virtualenvs/test/lib/python3.9/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/dan/.virtualenvs/test/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "/home/dan/.virtualenvs/test/lib/python3.9/site-packages/django/core/management/base.py", line 392, in check
    all_issues = checks.run_checks(
  File "/home/dan/.virtualenvs/test/lib/python3.9/site-packages/django/core/checks/registry.py", line 70, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/dan/.virtualenvs/test/lib/python3.9/site-packages/django/core/checks/model_checks.py", line 34, in check_all_models
    errors.extend(model.check(**kwargs))
  File "/home/dan/.virtualenvs/test/lib/python3.9/site-packages/django/db/models/base.py", line 1264, in check
    *cls._check_fields(**kwargs),
  File "/home/dan/.virtualenvs/test/lib/python3.9/site-packages/django/db/models/base.py", line 1343, in _check_fields
    errors.extend(field.check(**kwargs))
  File "/home/dan/.virtualenvs/test/lib/python3.9/site-packages/s3_file_field/fields.py", line 109, in check
    *self._check_supported_storage_provider(),
  File "/home/dan/.virtualenvs/test/lib/python3.9/site-packages/s3_file_field/fields.py", line 113, in _check_supported_storage_provider
    if not MultipartManager.supported_storage(self.storage):
  File "/home/dan/.virtualenvs/test/lib/python3.9/site-packages/s3_file_field/_multipart.py", line 134, in supported_storage
    cls.from_storage(storage)
  File "/home/dan/.virtualenvs/test/lib/python3.9/site-packages/s3_file_field/_multipart.py", line 125, in from_storage
    from ._multipart_minio import MinioMultipartManager
ImportError: cannot import name 'MinioMultipartManager' from partially initialized module 's3_file_field._multipart_minio' (most likely due to a circular import) (/home/dan/.virtualenvs/test/lib/python3.9/site-packages/s3_file_field/_multipart_minio.py)
```

**Comment by danlamanna** [comment]
This is now occurring almost 50% of the time django reloads the server. It seems like the easiest solution is to put the multipart managers in the same file. Another would be to move `from_storage` to a separate file as a utility function.

Random references:
- https://stackoverflow.com/questions/35179480/python-circular-imports-with-inheritance
- https://stackoverflow.com/questions/10113383/handle-circular-dependencies-in-python-modules
- https://stackoverflow.com/questions/1356304/are-circular-class-dependencies-bad-from-a-coding-style-point-of-view

**Comment by brianhelba** [comment]
@danlamanna I'm having trouble reproducing this. Is there a particular type of change or autoreload circumstances that tends to trigger this more? Do you have any thoughts as to how I can better reproduce this?

I'd like to explore whether an alternative import pattern fixes it, but reproducing is necessary for me to confirm anything.

**Comment by brianhelba** [comment]
@danlamanna Have you continued to see this ever? If not, I'll close the issue for now.

**Comment by danlamanna** [comment]
No, it stopped happening at some point.
